//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medway_Pratice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Blog
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Boş ola bilməz")]
        [DisplayName("Başlıq")]
        public string Title { get; set; }
          [Required(ErrorMessage = "Boş ola bilməz")]
        [DisplayName("Şəkil")]
        public string Photo { get; set; }
        [Required(ErrorMessage = "Boş ola bilməz")]
        [DisplayName("Tarix")]
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage = "Boş ola bilməz")]
        [DisplayName("Mətn")]
        public string Text { get; set; }
    }
}
