//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medway_Pratice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int OrderBy { get; set; }
        public string Name { get; set; }
        public string BgPhoto { get; set; }
        public string MainPhoto { get; set; }
        public string Icon { get; set; }
        public string Desc { get; set; }
        public string Text { get; set; }
    }
}
